### ISSUE TITLE
Create routes

### ISSUE THREAD

**Issue by SincerelyBrittany** [SincerelyBrittany/e-commerce-site-using-commerce.js#1]
Description: Please create routes for the application using [React Router](https://reactrouter.com/en/main)

Acceptance Criteria:

Routes to be created:

/home
/about
/products
/cart
/login
/signup
/contact

All routes should be able to render in the DOM with a simple message letting the developer know they landed on the correct page.
Please create test using https://testing-library.com/docs/example-react-router/

Please make pull request into the development branch :)

**Comment by REX-HERE** [comment]
hey, i would like to work on this. Please assign this to me

**Comment by SincerelyBrittany** [comment]
hi @REX-HERE, it is all yours :)

**Comment by SincerelyBrittany** [comment]
Great job and thank you again!
