### ISSUE TITLE
Responsive Products Page

### ISSUE THREAD

**Issue by SincerelyBrittany** [SincerelyBrittany/e-commerce-site-using-commerce.js#16]
**Description**
Right now there is nothing on the Products Page. We will eventually integrate the [commerce.js](url) api. But for now we should get some of the leg work done. Use [dummyjson.com](https://dummyjson.com/docs/products) to fetch a number of products and display them on cards, use bootstrap to design the page. Make sure the cards are responsive. Be sure to show the following on the card:

Name
Price 
And an add to cart button

The cards should look similar to this: 

A single card
<img width="327" alt="Screen Shot 2022-10-10 at 11 14 39 PM" src="https://user-images.githubusercontent.com/24905013/194988907-8c7cef69-844a-485e-90ce-0da876e04585.png">

Multiple cards
<img width="1051" alt="Screen Shot 2022-10-10 at 11 24 28 PM" src="https://user-images.githubusercontent.com/24905013/194990097-89faa4a4-f455-465b-a543-29ade8a4caad.png">

**Comment by najeebkp** [comment]
Hey @SincerelyBrittany please assign me this task

**Comment by SincerelyBrittany** [comment]
@najeebkp the task is all yours :)

**Comment by SincerelyBrittany** [comment]
Thank you! @najeebkp Great job
