### ISSUE TITLE
add products/:id page

### ISSUE THREAD

**Issue by SincerelyBrittany** [SincerelyBrittany/e-commerce-site-using-commerce.js#17]
Once https://github.com/SincerelyBrittany/e-commerce-site-using-commerce.js/issues/16 is completed. Make each product photo a button with the word "view" in it that redirects to the products/:id page. Make sure to use bootstrap for styling, when applicable.

Example below

<img width="357" alt="Screen Shot 2022-10-10 at 11 19 54 PM" src="https://user-images.githubusercontent.com/24905013/194989557-be75ba15-7e41-4f9b-8cfa-fa45bb326b8a.png">

**Comment by redxzeta** [comment]
can i work on this?

**Comment by SincerelyBrittany** [comment]
Sure @redxzeta, it is all yours.
