### ISSUE TITLE
Create a responsive navbar

### ISSUE THREAD

**Issue by SincerelyBrittany** [SincerelyBrittany/e-commerce-site-using-commerce.js#2]
Once issue https://github.com/SincerelyBrittany/e-commerce-site-using-commerce.js/issues/1 is completed, please install and use [bootstrap/sass](https://react-bootstrap.github.io/components/navbar/) to create a responsive navbar that goes to each route. Also add a image/svg of your choice for the logo. 

Navbar color: 
| gold | #FFD700 | rgb(255,215,0)

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi @SincerelyBrittany  kindly assign this issue to me so i can work on it

**Comment by DHRUVKHANDELWAL00** [comment]
hey @SincerelyBrittany  please assign it to me.

**Comment by SincerelyBrittany** [comment]
Hi @Muhammad-Shahid-Jamal, I have assigned this to you

**Comment by SincerelyBrittany** [comment]
> hey @SincerelyBrittany please assign it to me.

Hi @DHRUVKHANDELWAL00 I also need. a footer, are you available to complete that work?

**Comment by DHRUVKHANDELWAL00** [comment]
@SincerelyBrittany  yes i am avalaible. just give me all ur socials which u want at footer

**Comment by SincerelyBrittany** [comment]
Thank you!
