### ISSUE TITLE
Add a template About Us

### ISSUE THREAD

**Issue by SincerelyBrittany** [SincerelyBrittany/e-commerce-site-using-commerce.js#3]
I am hoping to allow others to use this template in the future. So I would like to add a template about us in the AboutUs.js. Pretty much use other about us pages for inspiration and create a template that any company can update with their information. Make sure to us the following HTML elements to indicate where they should update.

 h1 - Company Name 
image -Add a random image where they would put the company image 
Section - about the company (can use https://www.lipsum.com/)

Add anything else you see fit for a draft. Make sure to add descriptive class names for each.

**Comment by jagadyudha** [comment]
assign to me @SincerelyBrittany

**Comment by SincerelyBrittany** [comment]
Great job! Thank you again
